<?php

namespace LBreda\LaravelLangDb\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class RefreshLangDB extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'lbreda:refresh-lang-db';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Refreshes the language database';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->output->info('Refreshing data');

        foreach (self::$languages as $language) {
            DB::table('ldb_languages')->updateOrInsert(
                [
                    'native_name' => $language->native_name,
                ],
                [
                    'code_639_1'  => $language->code_639_1,
                    'code_639_2t' => $language->code_639_2t,
                    'code_639_2b' => $language->code_639_2b,
                    'code_639_3'  => $language->code_639_3,
                    'created_at'  => $language->created_at,
                    'updated_at'  => date('Y-m-d h:i:s'),
                    'deleted_at'  => $language->deleted_at,
                ]
            );
        }

        // End command
        $this->output->success('Data refreshed');

        return 0;
    }

    private static object $languages = (object)[
        [
            'code_639_1'  => 'ab',
            'code_639_2t' => 'abk',
            'code_639_2b' => 'abk',
            'code_639_3'  => 'abk',
            'native_name' => 'аҧсуа бызшәа, аҧсшәа',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'aa',
            'code_639_2t' => 'aar',
            'code_639_2b' => 'aar',
            'code_639_3'  => 'aar',
            'native_name' => 'Afaraf',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'af',
            'code_639_2t' => 'afr',
            'code_639_2b' => 'afr',
            'code_639_3'  => 'afr',
            'native_name' => 'Afrikaans',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ak',
            'code_639_2t' => 'aka',
            'code_639_2b' => 'aka',
            'code_639_3'  => 'aka',
            'native_name' => 'Akan',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sq',
            'code_639_2t' => 'sqi',
            'code_639_2b' => 'alb',
            'code_639_3'  => 'sqi',
            'native_name' => 'Shqip',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'am',
            'code_639_2t' => 'amh',
            'code_639_2b' => 'amh',
            'code_639_3'  => 'amh',
            'native_name' => 'አማርኛ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ar',
            'code_639_2t' => 'ara',
            'code_639_2b' => 'ara',
            'code_639_3'  => 'ara',
            'native_name' => 'العربية',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'an',
            'code_639_2t' => 'arg',
            'code_639_2b' => 'arg',
            'code_639_3'  => 'arg',
            'native_name' => 'aragonés',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'hy',
            'code_639_2t' => 'hye',
            'code_639_2b' => 'arm',
            'code_639_3'  => 'hye',
            'native_name' => 'Հայերեն',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'as',
            'code_639_2t' => 'asm',
            'code_639_2b' => 'asm',
            'code_639_3'  => 'asm',
            'native_name' => 'অসমীয়া',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'av',
            'code_639_2t' => 'ava',
            'code_639_2b' => 'ava',
            'code_639_3'  => 'ava',
            'native_name' => 'авар мацӀ, магӀарул мацӀ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ae',
            'code_639_2t' => 'ave',
            'code_639_2b' => 'ave',
            'code_639_3'  => 'ave',
            'native_name' => 'avesta',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ay',
            'code_639_2t' => 'aym',
            'code_639_2b' => 'aym',
            'code_639_3'  => 'aym',
            'native_name' => 'aymar aru',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'az',
            'code_639_2t' => 'aze',
            'code_639_2b' => 'aze',
            'code_639_3'  => 'aze',
            'native_name' => 'azərbaycan dili',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bm',
            'code_639_2t' => 'bam',
            'code_639_2b' => 'bam',
            'code_639_3'  => 'bam',
            'native_name' => 'bamanankan',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ba',
            'code_639_2t' => 'bak',
            'code_639_2b' => 'bak',
            'code_639_3'  => 'bak',
            'native_name' => 'башҡорт теле',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'eu',
            'code_639_2t' => 'eus',
            'code_639_2b' => 'baq',
            'code_639_3'  => 'eus',
            'native_name' => 'euskara, euskera',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'be',
            'code_639_2t' => 'bel',
            'code_639_2b' => 'bel',
            'code_639_3'  => 'bel',
            'native_name' => 'беларуская мова',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bn',
            'code_639_2t' => 'ben',
            'code_639_2b' => 'ben',
            'code_639_3'  => 'ben',
            'native_name' => 'বাংলা',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bh',
            'code_639_2t' => 'bih',
            'code_639_2b' => 'bih',
            'code_639_3'  => '',
            'native_name' => 'भोजपुरी',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bi',
            'code_639_2t' => 'bis',
            'code_639_2b' => 'bis',
            'code_639_3'  => 'bis',
            'native_name' => 'Bislama',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bs',
            'code_639_2t' => 'bos',
            'code_639_2b' => 'bos',
            'code_639_3'  => 'bos',
            'native_name' => 'bosanski jezik',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'br',
            'code_639_2t' => 'bre',
            'code_639_2b' => 'bre',
            'code_639_3'  => 'bre',
            'native_name' => 'brezhoneg',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bg',
            'code_639_2t' => 'bul',
            'code_639_2b' => 'bul',
            'code_639_3'  => 'bul',
            'native_name' => 'български език',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'my',
            'code_639_2t' => 'mya',
            'code_639_2b' => 'bur',
            'code_639_3'  => 'mya',
            'native_name' => 'ဗမာစာ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ca',
            'code_639_2t' => 'cat',
            'code_639_2b' => 'cat',
            'code_639_3'  => 'cat',
            'native_name' => 'català',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ch',
            'code_639_2t' => 'cha',
            'code_639_2b' => 'cha',
            'code_639_3'  => 'cha',
            'native_name' => 'Chamoru',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ce',
            'code_639_2t' => 'che',
            'code_639_2b' => 'che',
            'code_639_3'  => 'che',
            'native_name' => 'нохчийн мотт',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ny',
            'code_639_2t' => 'nya',
            'code_639_2b' => 'nya',
            'code_639_3'  => 'nya',
            'native_name' => 'chiCheŵa, chinyanja',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'zh',
            'code_639_2t' => 'zho',
            'code_639_2b' => 'chi',
            'code_639_3'  => 'zho',
            'native_name' => '中文 (Zhōngwén), 汉语, 漢語',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'cv',
            'code_639_2t' => 'chv',
            'code_639_2b' => 'chv',
            'code_639_3'  => 'chv',
            'native_name' => 'чӑваш чӗлхи',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kw',
            'code_639_2t' => 'cor',
            'code_639_2b' => 'cor',
            'code_639_3'  => 'cor',
            'native_name' => 'Kernewek',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'co',
            'code_639_2t' => 'cos',
            'code_639_2b' => 'cos',
            'code_639_3'  => 'cos',
            'native_name' => 'corsu, lingua corsa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'cr',
            'code_639_2t' => 'cre',
            'code_639_2b' => 'cre',
            'code_639_3'  => 'cre',
            'native_name' => 'ᓀᐦᐃᔭᐍᐏᐣ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'hr',
            'code_639_2t' => 'hrv',
            'code_639_2b' => 'hrv',
            'code_639_3'  => 'hrv',
            'native_name' => 'hrvatski jezik',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'cs',
            'code_639_2t' => 'ces',
            'code_639_2b' => 'cze',
            'code_639_3'  => 'ces',
            'native_name' => 'čeština, český jazyk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'da',
            'code_639_2t' => 'dan',
            'code_639_2b' => 'dan',
            'code_639_3'  => 'dan',
            'native_name' => 'dansk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'dv',
            'code_639_2t' => 'div',
            'code_639_2b' => 'div',
            'code_639_3'  => 'div',
            'native_name' => 'ދިވެހި',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nl',
            'code_639_2t' => 'nld',
            'code_639_2b' => 'dut',
            'code_639_3'  => 'nld',
            'native_name' => 'Nederlands, Vlaams',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'dz',
            'code_639_2t' => 'dzo',
            'code_639_2b' => 'dzo',
            'code_639_3'  => 'dzo',
            'native_name' => 'རྫོང་ཁ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'en',
            'code_639_2t' => 'eng',
            'code_639_2b' => 'eng',
            'code_639_3'  => 'eng',
            'native_name' => 'English',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'eo',
            'code_639_2t' => 'epo',
            'code_639_2b' => 'epo',
            'code_639_3'  => 'epo',
            'native_name' => 'Esperanto',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'et',
            'code_639_2t' => 'est',
            'code_639_2b' => 'est',
            'code_639_3'  => 'est',
            'native_name' => 'eesti, eesti keel',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ee',
            'code_639_2t' => 'ewe',
            'code_639_2b' => 'ewe',
            'code_639_3'  => 'ewe',
            'native_name' => 'Eʋegbe',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fo',
            'code_639_2t' => 'fao',
            'code_639_2b' => 'fao',
            'code_639_3'  => 'fao',
            'native_name' => 'føroyskt',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fj',
            'code_639_2t' => 'fij',
            'code_639_2b' => 'fij',
            'code_639_3'  => 'fij',
            'native_name' => 'vosa Vakaviti',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fi',
            'code_639_2t' => 'fin',
            'code_639_2b' => 'fin',
            'code_639_3'  => 'fin',
            'native_name' => 'suomi, suomen kieli',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fr',
            'code_639_2t' => 'fra',
            'code_639_2b' => 'fre',
            'code_639_3'  => 'fra',
            'native_name' => 'français, langue française',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ff',
            'code_639_2t' => 'ful',
            'code_639_2b' => 'ful',
            'code_639_3'  => 'ful',
            'native_name' => 'Fulfulde, Pulaar, Pular',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'gl',
            'code_639_2t' => 'glg',
            'code_639_2b' => 'glg',
            'code_639_3'  => 'glg',
            'native_name' => 'galego',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ka',
            'code_639_2t' => 'kat',
            'code_639_2b' => 'geo',
            'code_639_3'  => 'kat',
            'native_name' => 'ქართული',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'de',
            'code_639_2t' => 'deu',
            'code_639_2b' => 'ger',
            'code_639_3'  => 'deu',
            'native_name' => 'Deutsch',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'el',
            'code_639_2t' => 'ell',
            'code_639_2b' => 'gre',
            'code_639_3'  => 'ell',
            'native_name' => 'ελληνικά',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'gn',
            'code_639_2t' => 'grn',
            'code_639_2b' => 'grn',
            'code_639_3'  => 'grn',
            'native_name' => 'Avañe\'ẽ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'gu',
            'code_639_2t' => 'guj',
            'code_639_2b' => 'guj',
            'code_639_3'  => 'guj',
            'native_name' => 'ગુજરાતી',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ht',
            'code_639_2t' => 'hat',
            'code_639_2b' => 'hat',
            'code_639_3'  => 'hat',
            'native_name' => 'Kreyòl ayisyen',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ha',
            'code_639_2t' => 'hau',
            'code_639_2b' => 'hau',
            'code_639_3'  => 'hau',
            'native_name' => '(Hausa) هَوُسَ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'he',
            'code_639_2t' => 'heb',
            'code_639_2b' => 'heb',
            'code_639_3'  => 'heb',
            'native_name' => 'עברית',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'hz',
            'code_639_2t' => 'her',
            'code_639_2b' => 'her',
            'code_639_3'  => 'her',
            'native_name' => 'Otjiherero',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'hi',
            'code_639_2t' => 'hin',
            'code_639_2b' => 'hin',
            'code_639_3'  => 'hin',
            'native_name' => 'हिन्दी, हिंदी',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ho',
            'code_639_2t' => 'hmo',
            'code_639_2b' => 'hmo',
            'code_639_3'  => 'hmo',
            'native_name' => 'Hiri Motu',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'hu',
            'code_639_2t' => 'hun',
            'code_639_2b' => 'hun',
            'code_639_3'  => 'hun',
            'native_name' => 'magyar',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ia',
            'code_639_2t' => 'ina',
            'code_639_2b' => 'ina',
            'code_639_3'  => 'ina',
            'native_name' => 'Interlingua',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'id',
            'code_639_2t' => 'ind',
            'code_639_2b' => 'ind',
            'code_639_3'  => 'ind',
            'native_name' => 'Bahasa Indonesia',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ie',
            'code_639_2t' => 'ile',
            'code_639_2b' => 'ile',
            'code_639_3'  => 'ile',
            'native_name' => 'Originally called Occidental; then Interlingue after WWII',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ga',
            'code_639_2t' => 'gle',
            'code_639_2b' => 'gle',
            'code_639_3'  => 'gle',
            'native_name' => 'Gaeilge',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ig',
            'code_639_2t' => 'ibo',
            'code_639_2b' => 'ibo',
            'code_639_3'  => 'ibo',
            'native_name' => 'Asụsụ Igbo',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ik',
            'code_639_2t' => 'ipk',
            'code_639_2b' => 'ipk',
            'code_639_3'  => 'ipk',
            'native_name' => 'Iñupiaq, Iñupiatun',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'io',
            'code_639_2t' => 'ido',
            'code_639_2b' => 'ido',
            'code_639_3'  => 'ido',
            'native_name' => 'Ido',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'is',
            'code_639_2t' => 'isl',
            'code_639_2b' => 'ice',
            'code_639_3'  => 'isl',
            'native_name' => 'Íslenska',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'it',
            'code_639_2t' => 'ita',
            'code_639_2b' => 'ita',
            'code_639_3'  => 'ita',
            'native_name' => 'italiano',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'iu',
            'code_639_2t' => 'iku',
            'code_639_2b' => 'iku',
            'code_639_3'  => 'iku',
            'native_name' => 'ᐃᓄᒃᑎᑐᑦ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ja',
            'code_639_2t' => 'jpn',
            'code_639_2b' => 'jpn',
            'code_639_3'  => 'jpn',
            'native_name' => '日本語 (にほんご)',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'jv',
            'code_639_2t' => 'jav',
            'code_639_2b' => 'jav',
            'code_639_3'  => 'jav',
            'native_name' => 'basa Jawa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kl',
            'code_639_2t' => 'kal',
            'code_639_2b' => 'kal',
            'code_639_3'  => 'kal',
            'native_name' => 'kalaallisut, kalaallit oqaasii',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kn',
            'code_639_2t' => 'kan',
            'code_639_2b' => 'kan',
            'code_639_3'  => 'kan',
            'native_name' => 'ಕನ್ನಡ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kr',
            'code_639_2t' => 'kau',
            'code_639_2b' => 'kau',
            'code_639_3'  => 'kau',
            'native_name' => 'Kanuri',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ks',
            'code_639_2t' => 'kas',
            'code_639_2b' => 'kas',
            'code_639_3'  => 'kas',
            'native_name' => 'कश्मीरी, كشميري‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kk',
            'code_639_2t' => 'kaz',
            'code_639_2b' => 'kaz',
            'code_639_3'  => 'kaz',
            'native_name' => 'қазақ тілі',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'km',
            'code_639_2t' => 'khm',
            'code_639_2b' => 'khm',
            'code_639_3'  => 'khm',
            'native_name' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ki',
            'code_639_2t' => 'kik',
            'code_639_2b' => 'kik',
            'code_639_3'  => 'kik',
            'native_name' => 'Gĩkũyũ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'rw',
            'code_639_2t' => 'kin',
            'code_639_2b' => 'kin',
            'code_639_3'  => 'kin',
            'native_name' => 'Ikinyarwanda',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ky',
            'code_639_2t' => 'kir',
            'code_639_2b' => 'kir',
            'code_639_3'  => 'kir',
            'native_name' => 'Кыргызча, Кыргыз тили',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kv',
            'code_639_2t' => 'kom',
            'code_639_2b' => 'kom',
            'code_639_3'  => 'kom',
            'native_name' => 'коми кыв',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kg',
            'code_639_2t' => 'kon',
            'code_639_2b' => 'kon',
            'code_639_3'  => 'kon',
            'native_name' => 'Kikongo',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ko',
            'code_639_2t' => 'kor',
            'code_639_2b' => 'kor',
            'code_639_3'  => 'kor',
            'native_name' => '한국어, 조선어',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ku',
            'code_639_2t' => 'kur',
            'code_639_2b' => 'kur',
            'code_639_3'  => 'kur',
            'native_name' => 'Kurdî, كوردی‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'kj',
            'code_639_2t' => 'kua',
            'code_639_2b' => 'kua',
            'code_639_3'  => 'kua',
            'native_name' => 'Kuanyama',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'la',
            'code_639_2t' => 'lat',
            'code_639_2b' => 'lat',
            'code_639_3'  => 'lat',
            'native_name' => 'latine, lingua latina',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => '',
            'code_639_2t' => '',
            'code_639_2b' => '',
            'code_639_3'  => 'lld',
            'native_name' => 'ladin, lingua ladina',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lb',
            'code_639_2t' => 'ltz',
            'code_639_2b' => 'ltz',
            'code_639_3'  => 'ltz',
            'native_name' => 'Lëtzebuergesch',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lg',
            'code_639_2t' => 'lug',
            'code_639_2b' => 'lug',
            'code_639_3'  => 'lug',
            'native_name' => 'Luganda',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'li',
            'code_639_2t' => 'lim',
            'code_639_2b' => 'lim',
            'code_639_3'  => 'lim',
            'native_name' => 'Limburgs',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ln',
            'code_639_2t' => 'lin',
            'code_639_2b' => 'lin',
            'code_639_3'  => 'lin',
            'native_name' => 'Lingála',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lo',
            'code_639_2t' => 'lao',
            'code_639_2b' => 'lao',
            'code_639_3'  => 'lao',
            'native_name' => 'ພາສາລາວ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lt',
            'code_639_2t' => 'lit',
            'code_639_2b' => 'lit',
            'code_639_3'  => 'lit',
            'native_name' => 'lietuvių kalba',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lu',
            'code_639_2t' => 'lub',
            'code_639_2b' => 'lub',
            'code_639_3'  => 'lub',
            'native_name' => 'Tshiluba',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'lv',
            'code_639_2t' => 'lav',
            'code_639_2b' => 'lav',
            'code_639_3'  => 'lav',
            'native_name' => 'latviešu valoda',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'gv',
            'code_639_2t' => 'glv',
            'code_639_2b' => 'glv',
            'code_639_3'  => 'glv',
            'native_name' => 'Gaelg, Gailck',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mk',
            'code_639_2t' => 'mkd',
            'code_639_2b' => 'mac',
            'code_639_3'  => 'mkd',
            'native_name' => 'македонски јазик',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mg',
            'code_639_2t' => 'mlg',
            'code_639_2b' => 'mlg',
            'code_639_3'  => 'mlg',
            'native_name' => 'fiteny malagasy',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ms',
            'code_639_2t' => 'msa',
            'code_639_2b' => 'may',
            'code_639_3'  => 'msa',
            'native_name' => 'bahasa Melayu, بهاس ملايو‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ml',
            'code_639_2t' => 'mal',
            'code_639_2b' => 'mal',
            'code_639_3'  => 'mal',
            'native_name' => 'മലയാളം',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mt',
            'code_639_2t' => 'mlt',
            'code_639_2b' => 'mlt',
            'code_639_3'  => 'mlt',
            'native_name' => 'Malti',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mi',
            'code_639_2t' => 'mri',
            'code_639_2b' => 'mao',
            'code_639_3'  => 'mri',
            'native_name' => 'te reo Māori',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mr',
            'code_639_2t' => 'mar',
            'code_639_2b' => 'mar',
            'code_639_3'  => 'mar',
            'native_name' => 'मराठी',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mh',
            'code_639_2t' => 'mah',
            'code_639_2b' => 'mah',
            'code_639_3'  => 'mah',
            'native_name' => 'Kajin M̧ajeļ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'mn',
            'code_639_2t' => 'mon',
            'code_639_2b' => 'mon',
            'code_639_3'  => 'mon',
            'native_name' => 'монгол',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'na',
            'code_639_2t' => 'nau',
            'code_639_2b' => 'nau',
            'code_639_3'  => 'nau',
            'native_name' => 'Ekakairũ Naoero',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nv',
            'code_639_2t' => 'nav',
            'code_639_2b' => 'nav',
            'code_639_3'  => 'nav',
            'native_name' => 'Diné bizaad',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nd',
            'code_639_2t' => 'nde',
            'code_639_2b' => 'nde',
            'code_639_3'  => 'nde',
            'native_name' => 'isiNdebele',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ne',
            'code_639_2t' => 'nep',
            'code_639_2b' => 'nep',
            'code_639_3'  => 'nep',
            'native_name' => 'नेपाली',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ng',
            'code_639_2t' => 'ndo',
            'code_639_2b' => 'ndo',
            'code_639_3'  => 'ndo',
            'native_name' => 'Owambo',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nb',
            'code_639_2t' => 'nob',
            'code_639_2b' => 'nob',
            'code_639_3'  => 'nob',
            'native_name' => 'Norsk bokmål',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nn',
            'code_639_2t' => 'nno',
            'code_639_2b' => 'nno',
            'code_639_3'  => 'nno',
            'native_name' => 'Norsk nynorsk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'no',
            'code_639_2t' => 'nor',
            'code_639_2b' => 'nor',
            'code_639_3'  => 'nor',
            'native_name' => 'Norsk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ii',
            'code_639_2t' => 'iii',
            'code_639_2b' => 'iii',
            'code_639_3'  => 'iii',
            'native_name' => 'ꆈꌠ꒿ Nuosuhxop',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'nr',
            'code_639_2t' => 'nbl',
            'code_639_2b' => 'nbl',
            'code_639_3'  => 'nbl',
            'native_name' => 'isiNdebele',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'oc',
            'code_639_2t' => 'oci',
            'code_639_2b' => 'oci',
            'code_639_3'  => 'oci',
            'native_name' => 'occitan, lenga d\'òc',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'oj',
            'code_639_2t' => 'oji',
            'code_639_2b' => 'oji',
            'code_639_3'  => 'oji',
            'native_name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'cu',
            'code_639_2t' => 'chu',
            'code_639_2b' => 'chu',
            'code_639_3'  => 'chu',
            'native_name' => 'ѩзыкъ словѣньскъ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'om',
            'code_639_2t' => 'orm',
            'code_639_2b' => 'orm',
            'code_639_3'  => 'orm',
            'native_name' => 'Afaan Oromoo',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'or',
            'code_639_2t' => 'ori',
            'code_639_2b' => 'ori',
            'code_639_3'  => 'ori',
            'native_name' => 'ଓଡ଼ିଆ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'os',
            'code_639_2t' => 'oss',
            'code_639_2b' => 'oss',
            'code_639_3'  => 'oss',
            'native_name' => 'ирон æвзаг',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'pa',
            'code_639_2t' => 'pan',
            'code_639_2b' => 'pan',
            'code_639_3'  => 'pan',
            'native_name' => 'ਪੰਜਾਬੀ, پنجابی‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'pi',
            'code_639_2t' => 'pli',
            'code_639_2b' => 'pli',
            'code_639_3'  => 'pli',
            'native_name' => 'पाऴि',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fa',
            'code_639_2t' => 'fas',
            'code_639_2b' => 'per',
            'code_639_3'  => 'fas',
            'native_name' => 'فارسی',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'pl',
            'code_639_2t' => 'pol',
            'code_639_2b' => 'pol',
            'code_639_3'  => 'pol',
            'native_name' => 'język polski, polszczyzna',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ps',
            'code_639_2t' => 'pus',
            'code_639_2b' => 'pus',
            'code_639_3'  => 'pus',
            'native_name' => 'پښتو',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'pt',
            'code_639_2t' => 'por',
            'code_639_2b' => 'por',
            'code_639_3'  => 'por',
            'native_name' => 'português',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'qu',
            'code_639_2t' => 'que',
            'code_639_2b' => 'que',
            'code_639_3'  => 'que',
            'native_name' => 'Runa Simi, Kichwa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'rm',
            'code_639_2t' => 'roh',
            'code_639_2b' => 'roh',
            'code_639_3'  => 'roh',
            'native_name' => 'rumantsch grischun',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'rn',
            'code_639_2t' => 'run',
            'code_639_2b' => 'run',
            'code_639_3'  => 'run',
            'native_name' => 'Ikirundi',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ro',
            'code_639_2t' => 'ron',
            'code_639_2b' => 'rum',
            'code_639_3'  => 'ron',
            'native_name' => 'limba română',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ru',
            'code_639_2t' => 'rus',
            'code_639_2b' => 'rus',
            'code_639_3'  => 'rus',
            'native_name' => 'Русский',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sa',
            'code_639_2t' => 'san',
            'code_639_2b' => 'san',
            'code_639_3'  => 'san',
            'native_name' => 'संस्कृतम्',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sc',
            'code_639_2t' => 'srd',
            'code_639_2b' => 'srd',
            'code_639_3'  => 'srd',
            'native_name' => 'sardu',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sd',
            'code_639_2t' => 'snd',
            'code_639_2b' => 'snd',
            'code_639_3'  => 'snd',
            'native_name' => 'सिन्धी, سنڌي، سندھی‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'se',
            'code_639_2t' => 'sme',
            'code_639_2b' => 'sme',
            'code_639_3'  => 'sme',
            'native_name' => 'Davvisámegiella',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sm',
            'code_639_2t' => 'smo',
            'code_639_2b' => 'smo',
            'code_639_3'  => 'smo',
            'native_name' => 'gagana fa\'a Samoa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sg',
            'code_639_2t' => 'sag',
            'code_639_2b' => 'sag',
            'code_639_3'  => 'sag',
            'native_name' => 'yângâ tî sängö',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sr',
            'code_639_2t' => 'srp',
            'code_639_2b' => 'srp',
            'code_639_3'  => 'srp',
            'native_name' => 'српски језик',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'gd',
            'code_639_2t' => 'gla',
            'code_639_2b' => 'gla',
            'code_639_3'  => 'gla',
            'native_name' => 'Gàidhlig',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sn',
            'code_639_2t' => 'sna',
            'code_639_2b' => 'sna',
            'code_639_3'  => 'sna',
            'native_name' => 'chiShona',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'si',
            'code_639_2t' => 'sin',
            'code_639_2b' => 'sin',
            'code_639_3'  => 'sin',
            'native_name' => 'සිංහල',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sk',
            'code_639_2t' => 'slk',
            'code_639_2b' => 'slo',
            'code_639_3'  => 'slk',
            'native_name' => 'slovenčina, slovenský jazyk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sl',
            'code_639_2t' => 'slv',
            'code_639_2b' => 'slv',
            'code_639_3'  => 'slv',
            'native_name' => 'slovenski jezik, slovenščina',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'so',
            'code_639_2t' => 'som',
            'code_639_2b' => 'som',
            'code_639_3'  => 'som',
            'native_name' => 'Soomaaliga, af Soomaali',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'st',
            'code_639_2t' => 'sot',
            'code_639_2b' => 'sot',
            'code_639_3'  => 'sot',
            'native_name' => 'Sesotho',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'es',
            'code_639_2t' => 'spa',
            'code_639_2b' => 'spa',
            'code_639_3'  => 'spa',
            'native_name' => 'español',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'su',
            'code_639_2t' => 'sun',
            'code_639_2b' => 'sun',
            'code_639_3'  => 'sun',
            'native_name' => 'Basa Sunda',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sw',
            'code_639_2t' => 'swa',
            'code_639_2b' => 'swa',
            'code_639_3'  => 'swa',
            'native_name' => 'Kiswahili',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ss',
            'code_639_2t' => 'ssw',
            'code_639_2b' => 'ssw',
            'code_639_3'  => 'ssw',
            'native_name' => 'SiSwati',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'sv',
            'code_639_2t' => 'swe',
            'code_639_2b' => 'swe',
            'code_639_3'  => 'swe',
            'native_name' => 'svenska',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ta',
            'code_639_2t' => 'tam',
            'code_639_2b' => 'tam',
            'code_639_3'  => 'tam',
            'native_name' => 'தமிழ்',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'te',
            'code_639_2t' => 'tel',
            'code_639_2b' => 'tel',
            'code_639_3'  => 'tel',
            'native_name' => 'తెలుగు',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tg',
            'code_639_2t' => 'tgk',
            'code_639_2b' => 'tgk',
            'code_639_3'  => 'tgk',
            'native_name' => 'тоҷикӣ, toçikī, تاجیکی‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'th',
            'code_639_2t' => 'tha',
            'code_639_2b' => 'tha',
            'code_639_3'  => 'tha',
            'native_name' => 'ไทย',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ti',
            'code_639_2t' => 'tir',
            'code_639_2b' => 'tir',
            'code_639_3'  => 'tir',
            'native_name' => 'ትግርኛ',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'bo',
            'code_639_2t' => 'bod',
            'code_639_2b' => 'tib',
            'code_639_3'  => 'bod',
            'native_name' => 'བོད་ཡིག',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tk',
            'code_639_2t' => 'tuk',
            'code_639_2b' => 'tuk',
            'code_639_3'  => 'tuk',
            'native_name' => 'Türkmen, Түркмен',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tl',
            'code_639_2t' => 'tgl',
            'code_639_2b' => 'tgl',
            'code_639_3'  => 'tgl',
            'native_name' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tn',
            'code_639_2t' => 'tsn',
            'code_639_2b' => 'tsn',
            'code_639_3'  => 'tsn',
            'native_name' => 'Setswana',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'to',
            'code_639_2t' => 'ton',
            'code_639_2b' => 'ton',
            'code_639_3'  => 'ton',
            'native_name' => 'faka Tonga',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tr',
            'code_639_2t' => 'tur',
            'code_639_2b' => 'tur',
            'code_639_3'  => 'tur',
            'native_name' => 'Türkçe',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ts',
            'code_639_2t' => 'tso',
            'code_639_2b' => 'tso',
            'code_639_3'  => 'tso',
            'native_name' => 'Xitsonga',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tt',
            'code_639_2t' => 'tat',
            'code_639_2b' => 'tat',
            'code_639_3'  => 'tat',
            'native_name' => 'татар теле, tatar tele',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'tw',
            'code_639_2t' => 'twi',
            'code_639_2b' => 'twi',
            'code_639_3'  => 'twi',
            'native_name' => 'Twi',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ty',
            'code_639_2t' => 'tah',
            'code_639_2b' => 'tah',
            'code_639_3'  => 'tah',
            'native_name' => 'Reo Tahiti',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ug',
            'code_639_2t' => 'uig',
            'code_639_2b' => 'uig',
            'code_639_3'  => 'uig',
            'native_name' => 'ئۇيغۇرچە‎, Uyghurche',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'uk',
            'code_639_2t' => 'ukr',
            'code_639_2b' => 'ukr',
            'code_639_3'  => 'ukr',
            'native_name' => 'українська мова',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'ur',
            'code_639_2t' => 'urd',
            'code_639_2b' => 'urd',
            'code_639_3'  => 'urd',
            'native_name' => 'اردو',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'uz',
            'code_639_2t' => 'uzb',
            'code_639_2b' => 'uzb',
            'code_639_3'  => 'uzb',
            'native_name' => 'Oʻzbek, Ўзбек, أۇزبېك‎',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 've',
            'code_639_2t' => 'ven',
            'code_639_2b' => 'ven',
            'code_639_3'  => 'ven',
            'native_name' => 'Tshivenḓa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'vi',
            'code_639_2t' => 'vie',
            'code_639_2b' => 'vie',
            'code_639_3'  => 'vie',
            'native_name' => 'Việt Nam',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'vo',
            'code_639_2t' => 'vol',
            'code_639_2b' => 'vol',
            'code_639_3'  => 'vol',
            'native_name' => 'Volapük',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'wa',
            'code_639_2t' => 'wln',
            'code_639_2b' => 'wln',
            'code_639_3'  => 'wln',
            'native_name' => 'walon',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'cy',
            'code_639_2t' => 'cym',
            'code_639_2b' => 'wel',
            'code_639_3'  => 'cym',
            'native_name' => 'Cymraeg',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'wo',
            'code_639_2t' => 'wol',
            'code_639_2b' => 'wol',
            'code_639_3'  => 'wol',
            'native_name' => 'Wollof',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'fy',
            'code_639_2t' => 'fry',
            'code_639_2b' => 'fry',
            'code_639_3'  => 'fry',
            'native_name' => 'Frysk',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'xh',
            'code_639_2t' => 'xho',
            'code_639_2b' => 'xho',
            'code_639_3'  => 'xho',
            'native_name' => 'isiXhosa',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'yi',
            'code_639_2t' => 'yid',
            'code_639_2b' => 'yid',
            'code_639_3'  => 'yid',
            'native_name' => 'ייִדיש',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'yo',
            'code_639_2t' => 'yor',
            'code_639_2b' => 'yor',
            'code_639_3'  => 'yor',
            'native_name' => 'Yorùbá',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'za',
            'code_639_2t' => 'zha',
            'code_639_2b' => 'zha',
            'code_639_3'  => 'zha',
            'native_name' => 'Saɯ cueŋƅ, Saw cuengh',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
        [
            'code_639_1'  => 'zu',
            'code_639_2t' => 'zul',
            'code_639_2b' => 'zul',
            'code_639_3'  => 'zul',
            'native_name' => 'isiZulu',
            'created_at'  => '2021-01-15 00:00:00',
            'deleted_at'  => null,
        ],
    ];
}
